### ISSUE TITLE
time - 12 hour clock

### ISSUE THREAD

**Issue by Rahatrezaaa** [lucasrodes/whatstk#150]
### Discussed in https://github.com/lucasrodes/whatstk/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **Rahatrezaaa** April 16, 2024</sup>
In the dataframe, time is coming in 12 hour format, so no way to check if it is PM or AM.</div>

**Comment by lucasrodes** [comment]
Hi @Rahatrezaaa,
thanks fore your interest. In such circumstances, the automatic header detection can fail. 

For these cases, I'd suggest using the argument `hformat` and specify the header format of the chat text file. Learn about it [here](https://whatstk.readthedocs.io/en/develop/source/code_examples/load_chat_hformat.html).

**Comment by tinomuzo99** [comment]
Hi I am facing this issue too. My exported file is in the form of:
2019/02/13, 4:38 am - Messages and calls are end-to-end encrypted etc...
I had to specify the hformat argument:
hformat='%y/%m/%d, %P:%M - %name:')
 
I am still running into an issue because the next error I get is the following:
KeyError: "None of [Index(['date', 'username', 'message'], dtype='object')] are in the [columns]"

**Comment by lucasrodes** [comment]
Thanks for raising this issue. There is an issue in the documentation, which I am fixing now.

@tinomuzo99 you should use hformat '%y/%m/%d, %I:%M %P - %name:', where

- `%I`: 12-hour clock
- `%P`: PM/AM characters
